version: '3.9'

services:
  hello_user:
    build: .
    volumes:
      - .:/code
    command: sh -c "
      gradle clean
      &&
      gradle wrapper
      &&  
      ./gradlew test
      &&
      ./gradlew run
      " 
    environment:
      - ENVIRONMENT=developement
