/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.chackavack;

public class App {
    public String userName;
    public String getGreeting() {
        return "Hello ali!";
    }
    public void setUserName(String name){
        this.userName = name;
    }
    public String helloToUser(){
        return "Hello "+this.userName+"!";
    }

    public static void main(String[] args) {
        App app = new App();
        String userName = "Ali";
        app.setUserName(userName);
        System.out.println(app.helloToUser());
    }
}
